### ISSUE TITLE
Impact analysis fails to run

### ISSUE THREAD

**Issue by ADraginda** [acryldata/dbt-impact-action#3]
Error message

```
+ DBT_ARTIFACT_STATE_PATH=target-previous
+ python /home/runner/work/_actions/acryldata/dbt-impact-action/v1/src/impact_analysis.py
/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/pydantic/_internal/_config.py:261: UserWarning: Valid config keys have changed in V2:
* 'keep_untouched' has been renamed to 'ignored_types'
* 'schema_extra' has been renamed to 'json_schema_extra'
* 'underscore_attrs_are_private' has been removed
  warnings.warn(message, UserWarning)
Traceback (most recent call last):
  File "/home/runner/work/_actions/acryldata/dbt-impact-action/v1/src/impact_analysis.py", line 285, in main
ERROR: 5 validation errors for DatahubClientConfig
    output = dbt_impact_analysis()
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/datahub/telemetry/telemetry.py", line 379, in wrapper
    raise e
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/datahub/telemetry/telemetry.py", line 334, in wrapper
    res = func(*args, **kwargs)
  File "/home/runner/work/_actions/acryldata/dbt-impact-action/v1/src/impact_analysis.py", line 230, in dbt_impact_analysis
    graph = get_graph()
  File "/home/runner/work/_actions/acryldata/dbt-impact-action/v1/src/impact_analysis.py", line 26, in get_graph
    DatahubClientConfig(server=DATAHUB_SERVER, token=DATAHUB_TOKEN)
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/site-packages/pydantic/main.py", line 150, in __init__
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 5 validation errors for DatahubClientConfig
timeout_sec
  Field required [type=missing, input_value={'server': 'https://notio......u0w/'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.1.2/v/missing
```

**Comment by hsheth2** [comment]
Resolved by https://github.com/acryldata/dbt-impact-action/commit/38b2bccbbefecc52333677a4f2e0cc285a8ff133.
